### ISSUE TITLE
Segmentation fault on start of V1.22.7

### ISSUE THREAD

**Issue by nitschSB** [misery/DockerAusweisApp2#12]
Hello,

I cannot start the new versions of your image. V1.22.3 is working (havn't tried every version). I think that's not your fault, but you should consider offering versioned images.

```
default    <timestamp>   ReaderConfiguration](global/Env.h:123)
                 : Create singleton: governikus::ReaderConfiguration
Segmentation fault
```

```sh
docker run -d --name x11-bridge -e MODE="tcp" -e XPRA_HTML="yes" -e DISPLAY=:14 -e XPRA_PASSWORD=111 -p 10000:10000  jare/x11-bridge
docker run --rm --name ausweisapp2 --volumes-from x11-bridge -e DISPLAY=:14 -e LANG=DE --net=host aklitzing/ausweisapp2
```

**Comment by misery** [comment]
Thanks for your report and your cmdline to reproduce it.

```
#0  0x00007f032ba7e30e in QQmlPropertyCache::property(int) const () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#1  0x00007f032bae61bb in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#2  0x00007f032bae647c in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#3  0x00007f032bae44e1 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#4  0x00007f032bae4921 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#5  0x00007f032bae4c29 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#6  0x00007f032ba7943c in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#7  0x00007f032ba7d4b9 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#8  0x00007f032ba72be1 in QQmlDataBlob::tryDone() () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#9  0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#10 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#11 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#12 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#13 0x00007f032ba7c213 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#14 0x00007f032ba7e151 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#15 0x00007f032baad437 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#16 0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#17 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#18 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#19 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#20 0x00007f032ba7c213 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#21 0x00007f032ba7e151 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#22 0x00007f032baad437 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#23 0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#24 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#25 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#26 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#27 0x00007f032ba7c213 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#28 0x00007f032ba7e151 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#29 0x00007f032baad437 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#30 0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#31 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#32 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#33 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#34 0x00007f032ba7c213 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#35 0x00007f032ba7e151 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#36 0x00007f032baad437 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#37 0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#38 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#39 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#40 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#41 0x00007f032ba7c213 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#42 0x00007f032ba7e151 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#43 0x00007f032baad437 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#44 0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#45 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#46 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#47 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#48 0x00007f032ba7c213 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#49 0x00007f032ba7e151 in ?? () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#50 0x00007f032baad437 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#51 0x00007f032baad683 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#52 0x00007f032baadc9d in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#53 0x00007f032baaddcc in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5
#54 0x00007f032baaf60f in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /home/ausweisapp/libs/lib/libQt5Qml.so.5

```

This looks like a bug report of Qt that we already analysed. :-) That should be fixed in next major version.
https://bugreports.qt.io/browse/QTBUG-99545

Yes, I should create versioned images. Would accept a PR to add that in existing github actions if I add a tag. :-)

**Comment by nitschSB** [comment]
ok, good to know. Thank you, for your reply!

have a look at #13
